[[constraint]]
  name = "k8s.io/client-go"

[[constraint]]
  name = "github.com/argoproj/argo"
  branch = "master"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.3.0"

[[constraint]]
  name = "cloud.google.com/go"
  version = "~0.36.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "~1.1.1"

[[constraint]]
  name = "github.com/DataDog/datadog-go"
  version = "~2.1.0"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/argoproj/argo"
    unused-packages = false # Unused packages contains k8s generated models in the Argo project

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
