[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-7.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/argoproj/argo"
  version = "~2.2.1"

[[constraint]]
  name = "cloud.google.com/go"
  version = "~0.36.0"

[[constraint]]
  name = "github.com/google/uuid"
  version = "~1.1.1"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
